### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by spacey-sooty** [CurtinFRC/Team-Website#88]
We still need content. We have been waiting on it for ages. @Hazzer890 Do you need more people to work on content? If so I can probably find some more people.

**Comment by Hazzer890** [comment]
Sorry! Yeah, it might be worth it, ive got a limited amount of stuff. Best way to move forward is likely either you or someone you find just writes something, and then i can edit it. How does that sound?

**Comment by spacey-sooty** [comment]
> Sorry! Yeah, it might be worth it, ive got a limited amount of stuff. Best way to move forward is likely either you ro someone you find just writes something, and then i can edit it. How does that sound?

Sounds good to me! If your ok with it I'll do an anouncement in student anouncements asking for help with content for the website

**Comment by spacey-sooty** [comment]
Closing as this has good progress being made on it
